- id: autoflake
  name: autoflake
  entry: autoflake
  language: python
  files: \.py$
  exclude: (__init__.py|conftest.py)
  args: ['--in-place', '--remove-all-unused-imports']
  additional_dependencies: ["autoflake==1.3.1"]

- id: isort
  name: isort
  entry: isort
  language: python
  files: \.py$
  additional_dependencies: [
    "isort==5.4.1",
    "toml==0.10.1",
  ]

- id: black
  name: black
  entry: black
  language: python
  language_version: python
  files: \.py$
  additional_dependencies: [
    "git+https://github.com/psf/black.git@149b38d67430f0c580a05c821db767592e7d55e2",
  ]

- id: flake8
  name: flake8
  entry: flake8
  language: python
  files: \.py$
  args: ['--max-line-length=88']
  additional_dependencies: ["flake8==3.8.3"]
