- id: autoflake
  name: autoflake
  entry: autoflake
  language: python
  files: \.py$
  exclude: (__init__.py|conftest.py)
  args: ['--in-place', '--remove-all-unused-imports']
  additional_dependencies: ["autoflake==1.3"]

- id: isort
  name: isort
  entry: isort
  language: python
  files: \.py$
  additional_dependencies: [
    "isort==4.3.21",
    "toml==0.10.0",
  ]

- id: black
  name: black
  entry: black
  language: python
  language_version: python3.6
  files: \.py$
  additional_dependencies: [
    "git+https://github.com/psf/black.git@ffa676cd7d332e9fa5808d824f5a31f03ab9a5d0",
  ]

- id: flake8
  name: flake8
  entry: flake8
  language: python
  files: \.py$
  args: ['--max-line-length=88']
  additional_dependencies: ["flake8==3.7.8"]
