[tool.black]
line-length = 79
include = '\.pyi?$'

[tool.isort]
multi_line_output = 3
force_grid_wrap = 0
include_trailing_comma = true
use_parentheses = true
line_length = 79
default_section = "THIRDPARTY"
known_first_party = "tests"
not_skip = "__init__.py"

